name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-via-ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, dom, filter, gd, json

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

        env:
          APP_ENV: production
          DB_CONNECTION: mysql
          DB_HOST: localhost
          DB_PORT: 3306
          DB_DATABASE: c0votium
          DB_USERNAME: c0sal3767
          DB_PASSWORD: WJxmENtyMg)Xw

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: 31.207.34.207
          username: defaultadmin_votium.net
          password: xjgwe(!ORigeo
          local-dir: ./
          server-dir: /web/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/storage/*.key
            **/.env
            **/.env.*
            **/tests/**
            **/.editorconfig
            **/.styleci.yml
            **/phpunit.xml
            **/.gitattributes
            **/.gitignore
            **/README.md